<?php

namespace Tests;

use App\User;
use App\AccessControls;
use App\Foundation\Jwt\Services\GenerateJwt;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * sets and returns the bearerToken for the user.
     * @param User $user
     * @return string
     */
    protected function getBearerToken(User $user) {
        return resolve(GenerateJwt::class)->handle($user)['token'];
    }

    /**
     * sets and returns the bearerToken for the user.
     * @param User $user
     * @return string
     */
    protected function createAdminUser() {
        $user = factory(User::class, 1)->create()->first();
        $user->accessControls()->saveMany(AccessControls::all());
        $this->adminUser = $user->refresh();
        return $this->adminUser;
    }

    /**
     * Returns bearer token headers for requests
     * @param $token
     * @return array
     */
    protected function authHeader($token)
    {
        return [
            'Authorization' => 'Bearer ' .  $token
        ];
    }
}
